### ISSUE TITLE
Thoughts on making these work with Binder

### ISSUE THREAD

**Issue by vincentdavis** [tiagoantao/biopython-notebook#10]
http://mybinder.org/
I am giving it a try.

**Comment by tiagoantao** [comment]
This seems really cool

On 4 February 2016 at 11:45, Vincent <notifications@github.com> wrote:

> http://mybinder.org/
> I am giving it a try.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tiagoantao/biopython-notebook/issues/10>.
>



-- 
"While I may be sending this email outside my normal office hours, I have
no expectation to receive a reply outside yours" - @tomstafford

**Comment by tiagoantao** [comment]
@vincentdavis  Sorry for the delay with this and other issues. I integrated this with binder. I hope to get back to other pending issues ASAP.

**Comment by vincentdavis** [comment]
@tiagoantao Cool, Ill give it a try. I have been busy myself.
