### ISSUE TITLE
Support binder

### ISSUE THREAD

**Issue by tiagoantao** [tiagoantao/biopython-notebook#12]
Make sure this works with the binder service

**Comment by BioGeek** [comment]
Currently, when I click on the  `launch binder` button in the [README](https://github.com/tiagoantao/biopython-notebook/blob/master/README.md), I get the error:

```
This site can’t be reached
app.mybinder.org unexpectedly closed the connection.
ERR_CONNECTION_CLOSED
```

for URL [https://app.mybinder.org:80/2494897318](https://app.mybinder.org:80/2494897318)

(Chrome on Windows 7).

**Comment by tiagoantao** [comment]
I think this was a temporary problem with binder (given that it is a new service). It is currently working again.
