### ISSUE TITLE
Binder: Error loading tiagoantao/biopython-notebook/master!

### ISSUE THREAD

**Issue by gabriellovate** [tiagoantao/biopython-notebook#15]
![image](https://user-images.githubusercontent.com/39889038/82157459-f2204800-9857-11ea-9526-388ee7e2f496.png)

**Comment by fomightez** [comment]
The method of dealing with Binder in this repository is overly complex and not supported. (Dockerfiles are only to be used if all other approaches fail.) Until that is fixed, you can use the link below to run the notebooks in a Binder session that works:

[Direct launch a session with biopython notebooks from tiagoantao/biopython-notebook/ ](https://mybinder.org/v2/gh/fomightez/cl_sq_demo-binder/master/?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Ftiagoantao%252Fbiopython-notebook%26urlpath%3Dtree%252Fbiopython-notebook%252Fnotebooks%252F)

Explanation of why that works **as a work-around**:
My repository [here](https://github.com/fomightez/cl_sq_demo-binder) still launches a Binder session with  Biopython installed.  [nbgitpuller](https://jupyterhub.github.io/nbgitpuller/link) can be used to pull content from one repository into an environment sourced from another repository. So the above link uses nbgitpuller to launch a session with [my working environment specifications that includes biopython](https://github.com/fomightez/cl_sq_demo-binder) and then pulls content from tiagoantao/biopython-notebook/  . So you can use the latest posting of the notebooks still along with **CURRENT** biopython.

**Comment by tiagoantao** [comment]
PR applied, closing
