### ISSUE TITLE
Have automated testing of notebooks

### ISSUE THREAD

**Issue by tiagoantao** [tiagoantao/biopython-notebook#2]
As per the subject. As suggested by @vincentdavis.

See, for example https://github.com/bollwyvl/nosebook

**Comment by vincentdavis** [comment]
Commit  ec4b47d adds a notebook for testing other notebooks. This is not automated, should I make this into a python module that you can run on travis ci and/or run from a notebook? Maybe we want to tweek it?

**Comment by tiagoantao** [comment]
I think it would be better as a Python module, not a notebook (I think we
should hide this from beginners to avoid initial confusion). travis is
fundamental, me thinks.

Do you want me to tweak this myself, or do you prefer to do it yourself?

On 8 December 2015 at 19:42, Vincent <notifications@github.com> wrote:

> Commit ec4b47d
> <https://github.com/tiagoantao/biopython-notebook/commit/ec4b47d3058275ce7038b564044790e093814fdd>
> adds a notebook for testing other notebooks. This is not automated, should
> I make this into a python module that you can run on travis ci and/or run
> from a notebook? Maybe we want to tweek it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tiagoantao/biopython-notebook/issues/2#issuecomment-163088550>
> .
>



-- 
"Democracy matters more than any currency arrangement." - Paul Krugman

**Comment by vincentdavis** [comment]
I really know nothing about Travis CI. Probably better for you to do the
next iteration.


On Wednesday, December 9, 2015, Tiago Antao <notifications@github.com>
wrote:

> I think it would be better as a Python module, not a notebook (I think we
> should hide this from beginners to avoid initial confusion). travis is
> fundamental, me thinks.
>
> Do you want me to tweak this myself, or do you prefer to do it yourself?
>
> On 8 December 2015 at 19:42, Vincent <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Commit ec4b47d
> > <
> https://github.com/tiagoantao/biopython-notebook/commit/ec4b47d3058275ce7038b564044790e093814fdd
> >
> > adds a notebook for testing other notebooks. This is not automated,
> should
> > I make this into a python module that you can run on travis ci and/or run
> > from a notebook? Maybe we want to tweek it?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/tiagoantao/biopython-notebook/issues/2#issuecomment-163088550
> >
> > .
> >
>
>
>
> --
> "Democracy matters more than any currency arrangement." - Paul Krugman
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tiagoantao/biopython-notebook/issues/2#issuecomment-163371998>
> .
>


-- 
Sent from mobile app.
Vincent Davis
720-301-3003

**Comment by tiagoantao** [comment]
I have just changed your code in order to support travis. More details on
biopython-dev
Thanks

On 9 December 2015 at 13:17, Vincent <notifications@github.com> wrote:

> I really know nothing about Travis CI. Probably better for you to do the
> next iteration.
>
>
> On Wednesday, December 9, 2015, Tiago Antao <notifications@github.com>
> wrote:
>
> > I think it would be better as a Python module, not a notebook (I think we
> > should hide this from beginners to avoid initial confusion). travis is
> > fundamental, me thinks.
> >
> > Do you want me to tweak this myself, or do you prefer to do it yourself?
> >
> > On 8 December 2015 at 19:42, Vincent <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > Commit ec4b47d
> > > <
> >
> https://github.com/tiagoantao/biopython-notebook/commit/ec4b47d3058275ce7038b564044790e093814fdd
> > >
> > > adds a notebook for testing other notebooks. This is not automated,
> > should
> > > I make this into a python module that you can run on travis ci and/or
> run
> > > from a notebook? Maybe we want to tweek it?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/tiagoantao/biopython-notebook/issues/2#issuecomment-163088550
> > >
> > > .
> > >
> >
> >
> >
> > --
> > "Democracy matters more than any currency arrangement." - Paul Krugman
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/tiagoantao/biopython-notebook/issues/2#issuecomment-163371998
> >
> > .
> >
>
>
> --
> Sent from mobile app.
> Vincent Davis
> 720-301-3003
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tiagoantao/biopython-notebook/issues/2#issuecomment-163380397>
> .
>



-- 
"Democracy matters more than any currency arrangement." - Paul Krugman

**Comment by tiagoantao** [comment]
This is implemented (along with travis). Closing.
