### ISSUE TITLE
Reorganizing notebook names

### ISSUE THREAD

**Issue by tiagoantao** [tiagoantao/biopython-notebook#9]
I was planning on reorganizing notebook names. Mostly removing spaces and maybe even the numbering. The spaces on file names are problematic and there is really no ordering in chapter reading (save for one or two exceptions).

@vincentdavis if you are not OK with this, please say...

**Comment by vincentdavis** [comment]
I agree with removing the numbering.
Are you proposing a CamleCase naming? I think spaces are ok.
I was planning to write a little script to help keep the index up to date as notbooks are added or names chaged.

**Comment by tiagoantao** [comment]
I am divided with regards to spaces. As a rule they are bad in file names, but they make sense as notebook titles. camelCase is not common in Python: Either spaces or underscores.

With regards to the script that seems a good idea. In any case let me tell you my vision here:

1. Release a version that is close to the tutorial, call it version 1. This requires correcting quite some mistakes, which I plan to do soon. Release on biopython-dev, biopython lists.

2. Then stop to think where to take this. I think the tutorial is not very fit for a modern jupyter environment. Have the discussion on biopython-dev

So for now I would like to take this to a stable version, releasable. Then stop to think.

Say if you prefer a different strategy.

**Comment by vincentdavis** [comment]
I agree with your plan.

I have another person that may be willing to help out. She is very good at writing, trained in Molecular Biology and now an MD who does research and would like to learn python.

I was thinking about how the notebook could become an open hosted learning/experimenting environment.
